// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using asp.net_service.Persistance;

#nullable disable

namespace asp.net_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260118114142_SeedTokens")]
    partial class SeedTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("asp.net_service.Entities.EthTicker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EthTickers");
                });

            modelBuilder.Entity("asp.net_service.Entities.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tokens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f8574459-7035-4406-8d5e-a092a8e7eed2"),
                            Address = "0x8EdDd55579F72E99fCbe2fc9747edd46B1f032AC",
                            Name = "TopCOIN",
                            Symbol = "TC"
                        },
                        new
                        {
                            Id = new Guid("d91dfbbe-74b9-49df-a3e6-e75521b4222d"),
                            Address = "0x9c5956607797FdC78216FfDc4d608953eED655ad",
                            Name = "TopGEM",
                            Symbol = "TG"
                        },
                        new
                        {
                            Id = new Guid("710ebcf7-3d63-476d-b16c-56c80d6ede65"),
                            Address = "0x3b2a9049685AACb584789C630d8c3d1d15D77AbD",
                            Name = "MonkeyCoin",
                            Symbol = "MC"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
