// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using asp.net_service.Persistance;

#nullable disable

namespace asp.net_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("asp.net_service.Entities.EthTicker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EthTickers");
                });

            modelBuilder.Entity("asp.net_service.Entities.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tokens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9b5f9d2-5184-4969-b1b9-f63b2ef7a84c"),
                            Address = "0x8EdDd55579F72E99fCbe2fc9747edd46B1f032AC",
                            Name = "TopCOIN",
                            Symbol = "TC"
                        },
                        new
                        {
                            Id = new Guid("ed65fb76-1846-4872-a609-e1111cc1b982"),
                            Address = "0x9c5956607797FdC78216FfDc4d608953eED655ad",
                            Name = "TopGEM",
                            Symbol = "TG"
                        },
                        new
                        {
                            Id = new Guid("ca61d565-e728-40c5-bc8e-f1bb33a50446"),
                            Address = "0x3b2a9049685AACb584789C630d8c3d1d15D77AbD",
                            Name = "MonkeyCoin",
                            Symbol = "MC"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
